/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_yxhuang_androidnativehook_NativeHook */

#ifndef _Included_com_yxhuang_androidnativehook_NativeHook
#define _Included_com_yxhuang_androidnativehook_NativeHook
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_yxhuang_androidnativehook_NativeHook
 * Method:    writeText
 * Signature: (Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_yxhuang_androidnativehook_NativeHook_writeText
  (JNIEnv *, jobject, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
